name: Rust CI

on:
  push:
  pull_request:

permissions: {}

jobs:
  linting:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: "Set up Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false
          components: clippy, rustfmt

      - name: "Install Boost"
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev

      - name: "Check fmt"
        working-directory: floresta-ffi
        run: cargo fmt --all -- --check

      - name: "Check clippy"
        working-directory: floresta-ffi
        run: cargo clippy --all-targets -- -D warnings

  test:
    name: "Build and test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: "Set up Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false

      - name: "Install Boost"
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev

      - name: "Build"
        working-directory: floresta-ffi
        run: cargo build --locked

      - name: "Test"
        working-directory: floresta-ffi
        run: cargo test --locked
